### ISSUE TITLE
How about Structuring the single file into different contextual files

### ISSUE THREAD

**Issue by acpmasquerade** [ludbek/webpreview#1]

**Comment by ludbek** [comment]
since the code base is small did not bothered to create contextual modules but I too feel its a good practice. thanx for reminding :)

**Comment by acpmasquerade** [comment]
Not for a practice only but if you think expansion with features, you might find limited in future. that's why.

**Comment by ludbek** [comment]
not thinking of any new features right now but i did factorize the code though. i will continue doing so in future as per necessity.

**Comment by acpmasquerade** [comment]
:)
