### ISSUE TITLE
Replace strict versions in requirements.txt with acceptable version ranges

### ISSUE THREAD

**Issue by yuriiz** [ludbek/webpreview#10]
Pining exact version is bad practice because if webpreview is used in some project it will always use for example requests==2.10.0 even if there are improvement/security updates in this package.
Also if project has other dependency which requires newer version of this library, it will be impossible to be used together.
Instead requirements.txt should contain range from minimum required version to maximum (if it is incompatible with newer version of dependency) or just minimum version requirement (if there are no incompatibilities known with newer versions).
Related discussion:
https://github.com/pypa/setuptools/issues/894

**Comment by ludbek** [comment]
Yeah that is true. I have merged your pull request. Thanks :)

**Comment by ygbr** [comment]
Hi @ludbek can you merge my latest PR and push a new build to PyPI?

**Comment by ludbek** [comment]
@ygbr  I have merged your PR to  the master. Due to authentication issue at pypi I am not being able to publish updates. I will let you know once the issue it sorted out.

**Comment by ygbr** [comment]
Thanks @ludbek! Let me know if I can do anything to help with pypi.
