### ISSUE TITLE
Tweet title and image are returning None

### ISSUE THREAD

**Issue by osamajameelahmad** [ludbek/webpreview#21]
Hi tweet's preview image and the title is not working 
I am using the following peace of code:
`title, description, image = web_preview("https://twitter.com/realDonaldTrump/status/1290011569657610240?s=20",
                                            parser="html.parser")`
`print(title, description, image)`

Looking forward to hearing from you about this issue.
Osama

**Comment by ludbek** [comment]
I got `(None, "We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?", None)`.

`webpreview` does not handle javascript. Thats another feature we might need to work on.
