### ISSUE TITLE
Command-line tool not present while installing through pip

### ISSUE THREAD

**Issue by bewakes** [ludbek/webpreview#27]
Hi, this is a cool project! But I have issues with commandline tool.

System: MacOS arm64, python version 3.8.11

I did `pip install webpreview` but there is no command `webpreview`.

I even tried `python -m webpreview https://example.com` and it says: 'webpreview' is a package and cannot be directly executed.
Did I miss anything?

**Comment by ludbek** [comment]
Hey @bewakes , I am still working on to deploy the latest version. The command line tool is available only in version 1.7.0

**Comment by ludbek** [comment]
It should work now. Thanks for trying out. @bewakes
