### ISSUE TITLE
Relative Image Path

### ISSUE THREAD

**Issue by lucabezerra** [ludbek/webpreview#9]
Greetings!

First of all, thanks for the good work! :)

I'm having some trouble with extracting the data from a few URLs, namely the ones that have relative paths in the returned `image` value. For instance, when using https://understand.ai as the URL, I get `'images/banner.jpg'` in the `image` return. 

It would it be nice if this lib could return the image URL along with the domain, or even if the `web_preview()` method had an optional parameter where the user would choose whether he/she always wanted the absolute URL or the URL exactly as it's set in the original website, like:

`title, description, image = web_preview("aurl.com", absolute_url=True)`

Hope I made myself clear :)

Cheers!

**Comment by ludbek** [comment]
Sorry for the late reply.

In my opinion resolving the relative path to the absolute one is the proper solution.
I will let you know once I implement it. A PR is welcomed though :).

**Comment by lucabezerra** [comment]
I could probably make a PR that simply checks if the path has a schema (http://, https://) and if not, conclude that it's a relative path and concatenate the URL with it. However, if the path is something like `../media/file.jpg`, the backwards folder navigation would have to be dealt with and I'm kinda out of time to handle these edge cases now... Do you have any suggestions?

I've thought about using `urllib.parse.urlparse` to check, but it won't properly split the URL unless it has a schema - otherwise it considers the whole URL to be a path. I'm open to suggestions that make this task simpler to implement :)

**Comment by ludbek** [comment]
Hi, did some search and came across this [post](https://stackoverflow.com/questions/476511/resolving-a-relative-url-path-to-its-absolute-path).
Could you look into it and see if its a good fit for our use case?(if you are still into it :)

**Comment by lucabezerra** [comment]
Hey, I'm heading to a conference for the next 5 days, so depending on how's the rhythm there, I might be able to start something. I'll put this on my track to at least give some feedback whether I made it or not :)

**Comment by ludbek** [comment]
Cool, hope you have great time there.

**Comment by lucabezerra** [comment]
Thanks, it was pretty fun, indeed :)

Just so you know, I've finished writing the changes, but I'm going to ask a colleague to confirm a few questions I have before submitting the PR. Shouldn't take long now :)
